version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install flask boto3 flask-cors
  build:
    commands:
      - echo "Building Docker image"
      - docker build -t ai-backend .
      - docker tag ai-backend:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/ai-backend:latest
  post_build:
    commands:
      - echo "Pushing Docker image"
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/ai-backend:latest
artifacts:
  files:
    - '**/*'